require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")

-- 插件
require("plugins/lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/coc-nvim")
require("plugins/bufferline")
require("plugins/mason")
-- require("plugins/formatter")
-- require("plugins/nvim-dap/cpp")
require("plugins/dap/python")
require("plugins/dap/config")
require("plugins/dap/cpp")
require("plugins/dapui")
require("plugins/toggleterm")
require("plugins/indent-blankline")
require("plugins/comment")
require("plugins/nvim-ufo")
require("plugins/telescope")
require("plugins/dashboard")
require("plugins/scrollview")
require("plugins/neoscroll")
